# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfa47946f7bac9f5658a526821dc032f8e52948f97c143eea610b488fc9cc4cdccbf3aa86de06cf573c306862d929060dfd2e1de7887fc15882fa25d893b0446

test:
  secret_key_base: 016da715f9b2ade83b117849fb442b7ffb92b5d3d3053a4bca8a938c49ae8d31ff3754432ba7f02f1e9dd91239de0d94ef04a84fc437960cb61ec57b0062809a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
